[build]
builder = "DOCKERFILE"
dockerfilePath = "frontend/Dockerfile"
dockerContext = "frontend"

[deploy]
startCommand = "/start-frontend.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
