[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/Dockerfile.frontend"
dockerContext = ".."

[deploy]
startCommand = "/start-frontend.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
