[build]
builder = "DOCKERFILE"
dockerfilePath = "../docker/Dockerfile.backend"

[deploy]
startCommand = "/start-backend.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
