[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
dockerContext = "backend"

[deploy]
startCommand = "/start-backend.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
